<?php
namespace Database\Seeders;

use App\Models\Category;
use App\Models\TourPackage;
use App\Models\TourPackageImage;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TourPackagesSeeder extends Seeder
{
    public function run(): void
    {
        $categoryId = $this->resolveCategoryId();
        $baseDate = Carbon::now()->addDay()->startOfDay();

        DB::transaction(function () use ($categoryId, $baseDate) {
            foreach ($this->packages($baseDate) as $package) {
                $image = $package['image'] ?? null;
                unset($package['image']);
                unset($package['duration_days']);

                $tourPackage = TourPackage::updateOrCreate(
                    ['title' => $package['title']],
                    array_merge([
                        'category_id' => $categoryId,
                        'user_id' => 1,
                        'user_type' => 'admin',
                        'status' => 1,
                        'booking_person' => 0,
                        'average_rating' => 0,
                        'review_count' => 0,
                    ], $package)
                );

                if ($image && file_exists(base_path('assets/images/tour_package_image/' . $image))) {
                    TourPackageImage::updateOrCreate(
                        [
                            'tour_package_id' => $tourPackage->id,
                            'image' => $image,
                        ],
                        []
                    );
                }
            }
        });
    }

    private function resolveCategoryId(): int
    {
        $categoryId = Category::where('name', 'Tour Packages')->value('id');

        if ($categoryId) {
            return (int) $categoryId;
        }

        $fallbackId = Category::where('status', 1)->orderByDesc('id')->value('id');

        if ($fallbackId) {
            return (int) $fallbackId;
        }

        throw new \RuntimeException('No active category found for tour packages.');
    }

    private function packages(Carbon $baseDate): array
    {
        $image = '69fd07859d7321778190213.png';

        return [
            [
                'title' => 'Riyadh & Jeddah 5 Days Travel Package',
                'title_ar' => 'باقة الرياض وجدة 5 أيام',
                'tour_type' => 'Cultural / City Tour',
                'tour_type_ar' => 'ثقافة / جولة مدن',
                'package_label' => '5 Days Travel Package',
                'package_label_ar' => 'باقة سفر 5 أيام',
                'address' => 'Riyadh & Jeddah, Saudi Arabia',
                'address_ar' => 'الرياض وجدة، المملكة العربية السعودية',
                'city' => 'Riyadh, Jeddah',
                'country' => 'Saudi Arabia',
                'cities_covered' => 'Riyadh, Jeddah',
                'cities_covered_ar' => 'الرياض، جدة',
                'latitude' => null,
                'longitude' => null,
                'flexible_date' => 1,
                'day_nights' => '5 Days / 4 Nights',
                'person_capability' => 20,
                'price' => 450,
                'currency' => 'USD',
                'price_from' => 450,
                'price_to' => 900,
                'price_note' => 'Budget to mid-range package: $450 – $900 per person. Luxury upgrade: $1,200 – $2,200 per person. Price may vary depending on season, hotel level and availability.',
                'description' => 'Discover the heart of Saudi Arabia through a 5-day travel package covering Riyadh and Jeddah. This journey combines modern city life, rich heritage, cultural landmarks, comfortable transport, and memorable local experiences. Start in Riyadh with Boulevard Riyadh City, Kingdom Centre Tower, and Diriyah, then continue to Jeddah to explore the Corniche, Al-Balad historic district, and King Fahd Fountain.',
                'description_ar' => 'اكتشف قلب المملكة العربية السعودية من خلال باقة سفر لمدة 5 أيام تشمل الرياض وجدة. تجمع الرحلة بين الحياة العصرية والتراث الغني والمعالم الثقافية ووسائل النقل المريحة والتجارب المحلية المميزة. تبدأ الرحلة في الرياض بزيارة بوليفارد الرياض وبرج المملكة والدرعية، ثم تنتقل إلى جدة لاكتشاف الكورنيش ومنطقة البلد التاريخية ونافورة الملك فهد.',
                'destination_overview' => [
                    'departure_from' => 'Riyadh Airport',
                    'arrival' => 'Riyadh',
                    'transportation' => 'Airport transfers, private transportation, and domestic flight or land transfer between Riyadh and Jeddah',
                    'accommodation' => '4 nights accommodation with daily breakfast',
                    'cities_covered' => 'Riyadh, Jeddah',
                ],
                'departure_from_ar' => 'مطار الرياض',
                'arrival_ar' => 'الرياض',
                'transportation_ar' => 'انتقالات المطار، مواصلات خاصة، ورحلة داخلية أو انتقال بري بين الرياض وجدة',
                'accommodation_ar' => 'إقامة 4 ليالٍ مع إفطار يومي',
                'features' => [
                    ['icon' => 'fa-solid fa-landmark', 'feature' => 'History'],
                    ['icon' => 'fa-solid fa-palette', 'feature' => 'Culture'],
                    ['icon' => 'fa-solid fa-city', 'feature' => 'Modern city life'],
                    ['icon' => 'fa-solid fa-hotel', 'feature' => 'Hospitality'],
                    ['icon' => 'fa-solid fa-bus', 'feature' => 'Comfortable transport'],
                    ['icon' => 'fa-solid fa-map-location-dot', 'feature' => 'Guided tours'],
                ],
                'destination_features_ar' => [
                    ['icon' => 'fa-solid fa-landmark', 'feature' => 'تاريخ'],
                    ['icon' => 'fa-solid fa-palette', 'feature' => 'ثقافة'],
                    ['icon' => 'fa-solid fa-city', 'feature' => 'حياة عصرية'],
                    ['icon' => 'fa-solid fa-hotel', 'feature' => 'ضيافة'],
                    ['icon' => 'fa-solid fa-bus', 'feature' => 'مواصلات مريحة'],
                    ['icon' => 'fa-solid fa-map-location-dot', 'feature' => 'جولات سياحية'],
                ],
                'highlights' => [
                    'Explore two amazing cities',
                    'Rich heritage and culture',
                    'Comfortable transport',
                    'Unforgettable experiences',
                    'Safe, reliable and convenient',
                ],
                'destination_highlights_ar' => [
                    'استكشاف مدينتين مميزتين',
                    'تراث وثقافة غنية',
                    'مواصلات مريحة',
                    'تجارب لا تُنسى',
                    'رحلة آمنة وموثوقة ومريحة',
                ],
                'includes' => [
                    '4★ hotels in Riyadh & Jeddah',
                    '4 nights accommodation with daily breakfast',
                    'Airport / hotel transfers',
                    'Domestic flight Riyadh ⇄ Jeddah or private car transfer',
                    'Private transportation for tours and sightseeing',
                    'Guided sightseeing tours with local guides',
                ],
                'includes_ar' => [
                    'فنادق 4 نجوم في الرياض وجدة',
                    'إقامة 4 ليالٍ مع إفطار يومي',
                    'انتقالات من وإلى المطار والفندق',
                    'رحلة داخلية بين الرياض وجدة أو انتقال بسيارة خاصة',
                    'مواصلات خاصة للجولات والمعالم السياحية',
                    'جولات سياحية بإرشاد محلي',
                ],
                'excludes' => [
                    'International flight',
                    'Visa',
                    'Entry tickets unless mentioned',
                    'Personal expenses',
                    'Meals not mentioned',
                ],
                'excludes_ar' => [
                    'التأشيرة',
                    'المصاريف الشخصية',
                    'تذاكر الدخول ما لم يتم ذكرها',
                    'الوجبات غير المذكورة',
                    'تأمين السفر ما لم يتم ذكره',
                ],
                'itinerary_days' => [
                    ['day_number' => 'Day 1', 'title' => 'Arrival in Riyadh', 'title_ar' => 'الوصول إلى الرياض', 'description' => 'Airport transfer and hotel check-in with free time to relax.', 'description_ar' => 'الاستقبال من المطار وتسجيل الوصول إلى الفندق مع وقت حر للراحة.'],
                    ['day_number' => 'Day 2', 'title' => 'Riyadh Tour', 'title_ar' => 'جولة في الرياض', 'description' => 'Visit Boulevard Riyadh City, Kingdom Centre Tower, and Diriyah.', 'description_ar' => 'زيارة بوليفارد الرياض وبرج المملكة والدرعية.'],
                    ['day_number' => 'Day 3', 'title' => 'Travel to Jeddah', 'title_ar' => 'السفر إلى جدة', 'description' => 'Travel to Jeddah and enjoy the evening at leisure.', 'description_ar' => 'السفر إلى جدة والاستمتاع بمساء حر.'],
                    ['day_number' => 'Day 4', 'title' => 'Jeddah Tour', 'title_ar' => 'جولة في جدة', 'description' => 'Explore the Corniche, Al-Balad historic district, and King Fahd Fountain.', 'description_ar' => 'استكشاف الكورنيش ومنطقة البلد التاريخية ونافورة الملك فهد.'],
                    ['day_number' => 'Day 5', 'title' => 'Departure', 'title_ar' => 'المغادرة', 'description' => 'Transfer to the airport for final departure.', 'description_ar' => 'الانتقال إلى المطار للمغادرة النهائية.'],
                ],
                'tour_start' => $baseDate->copy()->toDateTimeString(),
                'tour_end' => $baseDate->copy()->addDay()->toDateTimeString(),
            ],
            [
                'title' => 'Thailand 7 Days Travel Package',
                'title_ar' => 'باقة تايلاند 7 أيام',
                'tour_type' => 'Beach / Culture / Adventure',
                'tour_type_ar' => 'شاطئ / ثقافة / مغامرة',
                'package_label' => '7 Days Travel Package',
                'package_label_ar' => 'باقة سفر 7 أيام',
                'address' => 'Bangkok, Pattaya, Phuket, Thailand',
                'address_ar' => 'بانكوك، باتايا، بوكيت، تايلاند',
                'city' => 'Bangkok, Pattaya, Phuket',
                'country' => 'Thailand',
                'cities_covered' => 'Bangkok, Pattaya, Phuket',
                'cities_covered_ar' => 'بانكوك، باتايا، بوكيت',
                'latitude' => null,
                'longitude' => null,
                'flexible_date' => 1,
                'day_nights' => '7 Days / 6 Nights',
                'person_capability' => 20,
                'price' => 900,
                'currency' => 'USD',
                'price_from' => 900,
                'price_to' => 1600,
                'price_note' => 'Budget to mid-range package: $900 – $1,600 per person. Luxury upgrade: $2,000 – $3,500 per person. Prices vary depending on season, flight timing, hotel level and availability.',
                'description' => 'Discover Thailand through a 7-day travel package combining exotic beaches, rich culture, city tours, island experiences, shopping, relaxation, adventure, and unforgettable memories.',
                'description_ar' => 'اكتشف تايلاند من خلال باقة سفر لمدة 7 أيام تجمع بين الشواطئ الساحرة والثقافة الغنية والجولات السياحية وتجارب الجزر والتسوق والاسترخاء والمغامرة والذكريات التي لا تُنسى.',
                'destination_overview' => [
                    'departure_from' => 'Bangkok Airport',
                    'arrival' => 'Bangkok',
                    'transportation' => 'Airport transfers, domestic transfers between Bangkok, Pattaya and Phuket, and guided tour transportation',
                    'accommodation' => '6 nights hotel accommodation with daily breakfast',
                    'cities_covered' => 'Bangkok, Pattaya, Phuket',
                ],
                'departure_from_ar' => 'مطار بانكوك',
                'arrival_ar' => 'بانكوك',
                'transportation_ar' => 'انتقالات المطار والتنقلات الداخلية بين بانكوك وباتايا وبوكيت ومواصلات الجولات السياحية',
                'accommodation_ar' => 'إقامة فندقية لمدة 6 ليالٍ مع إفطار يومي',
                'features' => [
                    ['icon' => 'fa-solid fa-umbrella-beach', 'feature' => 'Exotic beaches'],
                    ['icon' => 'fa-solid fa-palette', 'feature' => 'Rich culture'],
                    ['icon' => 'fa-solid fa-ship', 'feature' => 'Island trips'],
                    ['icon' => 'fa-solid fa-ship', 'feature' => 'Boat excursions'],
                    ['icon' => 'fa-solid fa-bag-shopping', 'feature' => 'Shopping'],
                    ['icon' => 'fa-solid fa-person-hiking', 'feature' => 'Adventure'],
                    ['icon' => 'fa-solid fa-users', 'feature' => 'Family friendly'],
                    ['icon' => 'fa-solid fa-spa', 'feature' => 'Relaxation'],
                ],
                'destination_features_ar' => [
                    ['icon' => 'fa-solid fa-umbrella-beach', 'feature' => 'شواطئ ساحرة'],
                    ['icon' => 'fa-solid fa-palette', 'feature' => 'ثقافة غنية'],
                    ['icon' => 'fa-solid fa-ship', 'feature' => 'رحلات جزر'],
                    ['icon' => 'fa-solid fa-ship', 'feature' => 'جولات بحرية'],
                    ['icon' => 'fa-solid fa-bag-shopping', 'feature' => 'تسوق'],
                    ['icon' => 'fa-solid fa-person-hiking', 'feature' => 'مغامرة'],
                    ['icon' => 'fa-solid fa-users', 'feature' => 'مناسب للعائلات'],
                    ['icon' => 'fa-solid fa-spa', 'feature' => 'استرخاء'],
                ],
                'highlights' => [
                    'Stunning temples and culture',
                    'Beautiful islands and beaches',
                    'Delicious food and nightlife',
                    'Shopping and local experiences',
                    'Relaxation and adventure',
                    'Perfect for couples, families, friends and solo travelers',
                ],
                'destination_highlights_ar' => [
                    'معابد وثقافة مميزة',
                    'جزر وشواطئ جميلة',
                    'طعام رائع وحياة ليلية',
                    'تسوق وتجارب محلية',
                    'استرخاء ومغامرة',
                    'مناسب للأزواج والعائلات والأصدقاء والمسافرين بمفردهم',
                ],
                'includes' => [
                    'Round-trip international flight economy',
                    '3★ to 4★ hotel accommodation for 6 nights',
                    'Daily breakfast',
                    'Airport transfers',
                    'Domestic transfers between Bangkok, Pattaya and Phuket',
                    'Guided sightseeing tours',
                    'Entrance tickets for selected attractions',
                    'Island trips and boat excursions',
                ],
                'includes_ar' => [
                    'تذكرة طيران دولية ذهاب وعودة على الدرجة الاقتصادية',
                    'إقامة فندقية من 3 إلى 4 نجوم لمدة 6 ليالٍ',
                    'إفطار يومي',
                    'انتقالات المطار',
                    'تنقلات داخلية بين بانكوك وباتايا وبوكيت',
                    'جولات سياحية بإرشاد محلي',
                    'تذاكر دخول للمعالم المختارة',
                    'رحلات جزر وتجارب بحرية',
                ],
                'excludes' => [
                    'Visa',
                    'Personal expenses',
                    'Optional activities',
                    'Meals not mentioned',
                    'Early check-in or late check-out',
                    'Travel insurance unless mentioned',
                ],
                'excludes_ar' => [
                    'التأشيرة',
                    'المصاريف الشخصية',
                    'الأنشطة الاختيارية',
                    'الوجبات غير المذكورة',
                    'تسجيل الوصول المبكر أو المغادرة المتأخرة',
                    'تأمين السفر ما لم يتم ذكره',
                ],
                'itinerary_days' => [
                    ['day_number' => 'Day 1', 'title' => 'Arrival in Bangkok', 'title_ar' => 'الوصول إلى بانكوك', 'description' => 'Airport transfer to hotel and free evening.', 'description_ar' => 'الاستقبال من المطار والانتقال إلى الفندق ومساء حر.'],
                    ['day_number' => 'Day 2', 'title' => 'Bangkok City Tour', 'title_ar' => 'جولة في بانكوك', 'description' => 'Grand Palace, Wat Pho, Wat Arun and Chao Phraya River cruise.', 'description_ar' => 'زيارة القصر الكبير ووات فو ووات أرون ورحلة في نهر تشاو فرايا.'],
                    ['day_number' => 'Day 3', 'title' => 'Pattaya Day Trip', 'title_ar' => 'رحلة إلى باتايا', 'description' => 'Coral Island tour, beach activities and water sports.', 'description_ar' => 'جولة جزيرة كورال والأنشطة الشاطئية والرياضات المائية.'],
                    ['day_number' => 'Day 4', 'title' => 'Travel to Phuket', 'title_ar' => 'الانتقال إلى بوكيت', 'description' => 'Hotel transfer and domestic flight, then free evening.', 'description_ar' => 'انتقال إلى الفندق ورحلة داخلية ثم مساء حر.'],
                    ['day_number' => 'Day 5', 'title' => 'Phi Phi Islands Tour', 'title_ar' => 'جولة جزر في في', 'description' => 'Speedboat trip, snorkeling and beautiful beaches.', 'description_ar' => 'رحلة بالقارب السريع وسنوركلينج وشواطئ جميلة.'],
                    ['day_number' => 'Day 6', 'title' => 'Phuket Leisure Day', 'title_ar' => 'يوم حر في بوكيت', 'description' => 'Optional James Bond Island, shopping, beach or spa.', 'description_ar' => 'اختيار رحلة جزيرة جيمس بوند أو التسوق أو الاسترخاء على الشاطئ أو في السبا.'],
                    ['day_number' => 'Day 7', 'title' => 'Departure', 'title_ar' => 'المغادرة', 'description' => 'Airport transfer and return flight.', 'description_ar' => 'الانتقال إلى المطار والعودة بالطائرة.'],
                ],
                'tour_start' => $baseDate->copy()->toDateTimeString(),
                'tour_end' => $baseDate->copy()->addDays(7)->toDateTimeString(),
            ],
            [
                'title' => 'France Paris 7 Days Travel Package',
                'title_ar' => 'باقة باريس فرنسا 7 أيام',
                'tour_type' => 'Romance / Culture / City Tour',
                'tour_type_ar' => 'رومانسية / ثقافة / جولة مدينة',
                'package_label' => '7 Days Travel Package',
                'package_label_ar' => 'باقة سفر 7 أيام',
                'address' => 'Paris, France',
                'address_ar' => 'باريس، فرنسا',
                'city' => 'Paris',
                'country' => 'France',
                'cities_covered' => 'Paris',
                'cities_covered_ar' => 'باريس',
                'latitude' => '48.8566',
                'longitude' => '2.3522',
                'flexible_date' => 1,
                'day_nights' => '7 Days / 6 Nights',
                'person_capability' => 20,
                'price' => 1800,
                'currency' => 'USD',
                'price_from' => 1800,
                'price_to' => 2800,
                'price_note' => 'Budget to mid-range package: $1,800 – $2,800 per person. Luxury option starts from $4,500+ per person. Best time to visit: April to October.',
                'description' => 'Live the magic of Paris through a 7-day travel package filled with culture, romance, famous landmarks, river cruises, museums, shopping, and unforgettable memories. Explore the Eiffel Tower, Seine River, Disneyland Paris, Versailles Palace, Montmartre and Sacré-Cœur.',
                'description_ar' => 'عِش سحر باريس من خلال باقة سفر لمدة 7 أيام تجمع بين الثقافة والرومانسية والمعالم الشهيرة والرحلات النهرية والمتاحف والتسوق والذكريات التي لا تُنسى. استكشف برج إيفل ونهر السين وديزني لاند باريس وقصر فرساي ومونمارتر وكنيسة القلب المقدس.',
                'destination_overview' => [
                    'departure_from' => 'Paris Airport',
                    'arrival' => 'Paris',
                    'transportation' => 'Airport transfers, 7-day metro pass and guided tour transportation',
                    'accommodation' => '6 nights accommodation in central Paris with breakfast',
                    'cities_covered' => 'Paris',
                ],
                'departure_from_ar' => 'مطار باريس',
                'arrival_ar' => 'باريس',
                'transportation_ar' => 'انتقالات المطار، بطاقة مترو لمدة 7 أيام، ومواصلات للجولات السياحية',
                'accommodation_ar' => 'إقامة 6 ليالٍ في وسط باريس مع الإفطار',
                'features' => [
                    ['icon' => 'fa-solid fa-heart', 'feature' => 'Romance'],
                    ['icon' => 'fa-solid fa-palette', 'feature' => 'Culture'],
                    ['icon' => 'fa-solid fa-monument', 'feature' => 'Landmarks'],
                    ['icon' => 'fa-solid fa-building-columns', 'feature' => 'Museums'],
                    ['icon' => 'fa-solid fa-bag-shopping', 'feature' => 'Shopping'],
                    ['icon' => 'fa-solid fa-users', 'feature' => 'Family friendly'],
                ],
                'destination_features_ar' => [
                    ['icon' => 'fa-solid fa-heart', 'feature' => 'رومانسية'],
                    ['icon' => 'fa-solid fa-palette', 'feature' => 'ثقافة'],
                    ['icon' => 'fa-solid fa-monument', 'feature' => 'معالم'],
                    ['icon' => 'fa-solid fa-building-columns', 'feature' => 'متاحف'],
                    ['icon' => 'fa-solid fa-bag-shopping', 'feature' => 'تسوق'],
                    ['icon' => 'fa-solid fa-users', 'feature' => 'مناسب للعائلات'],
                ],
                'highlights' => [
                    'Live the magic of Paris',
                    'Eiffel Tower and Seine River',
                    'Disneyland Paris',
                    'Versailles Palace',
                    'Romantic city experiences',
                    'Shopping and cafés',
                ],
                'destination_highlights_ar' => [
                    'عِش سحر باريس',
                    'برج إيفل ونهر السين',
                    'ديزني لاند باريس',
                    'قصر فرساي',
                    'تجارب رومانسية',
                    'تسوق ومقاهي',
                ],
                'includes' => [
                    'Round-trip international flight economy class',
                    '4★ hotel in central Paris with breakfast',
                    'Airport transfers',
                    '7-day metro pass',
                    'Day trips to Versailles and Disneyland Paris',
                    'Basic sightseeing tours in Paris',
                ],
                'includes_ar' => [
                    'تذكرة طيران دولية ذهاب وعودة على الدرجة الاقتصادية',
                    'فندق 4 نجوم في وسط باريس مع الإفطار',
                    'انتقالات المطار',
                    'بطاقة مترو لمدة 7 أيام',
                    'رحلات يومية إلى فرساي وديزني لاند باريس',
                    'جولات سياحية أساسية في باريس',
                ],
                'excludes' => [
                    'Visa',
                    'Personal expenses',
                    'Optional activities',
                    'Meals not mentioned',
                    'Travel insurance unless mentioned',
                ],
                'excludes_ar' => [
                    'التأشيرة',
                    'المصاريف الشخصية',
                    'الأنشطة الاختيارية',
                    'الوجبات غير المذكورة',
                    'تأمين السفر ما لم يتم ذكره',
                ],
                'itinerary_days' => [
                    ['day_number' => 'Day 1', 'title' => 'Arrival in Paris', 'title_ar' => 'الوصول إلى باريس', 'description' => 'Hotel check-in and free time to relax.', 'description_ar' => 'تسجيل الوصول في الفندق ووقت حر للاسترخاء.'],
                    ['day_number' => 'Day 2', 'title' => 'Eiffel Tower, Seine Cruise & City Tour', 'title_ar' => 'برج إيفل ورحلة نهر السين وجولة المدينة', 'description' => 'Discover Paris’ most famous landmarks.', 'description_ar' => 'اكتشاف أشهر معالم باريس.'],
                    ['day_number' => 'Day 3', 'title' => 'Disneyland Paris', 'title_ar' => 'ديزني لاند باريس', 'description' => 'Full magical day for all ages.', 'description_ar' => 'يوم كامل مليء بالسحر لجميع الأعمار.'],
                    ['day_number' => 'Day 4', 'title' => 'Versailles Palace Day Trip', 'title_ar' => 'رحلة إلى قصر فرساي', 'description' => 'Explore the royal beauty of Versailles.', 'description_ar' => 'استكشاف جمال قصر فرساي الملكي.'],
                    ['day_number' => 'Day 5', 'title' => 'Montmartre & Sacré-Cœur', 'title_ar' => 'مونمارتر وكنيسة القلب المقدس', 'description' => 'Art, history and breathtaking views.', 'description_ar' => 'فن وتاريخ وإطلالات رائعة.'],
                    ['day_number' => 'Day 6', 'title' => 'Free Day / Shopping', 'title_ar' => 'يوم حر / تسوق', 'description' => 'Enjoy Paris your way with shopping, cafés and more.', 'description_ar' => 'استمتع بباريس بطريقتك مع التسوق والمقاهي والمزيد.'],
                    ['day_number' => 'Day 7', 'title' => 'Departure', 'title_ar' => 'المغادرة', 'description' => 'Check-out and transfer to airport.', 'description_ar' => 'تسجيل المغادرة والانتقال إلى المطار.'],
                ],
                'tour_start' => $baseDate->copy()->toDateTimeString(),
                'tour_end' => $baseDate->copy()->addDays(7)->toDateTimeString(),
            ],
            [
                'title' => 'Egypt 7 Days Travel Package',
                'title_ar' => 'باقة مصر 7 أيام',
                'tour_type' => 'History / Culture / Nile Experience',
                'tour_type_ar' => 'تاريخ / ثقافة / تجربة نيلية',
                'package_label' => '7 Days / 6 Nights',
                'package_label_ar' => '7 أيام / 6 ليالٍ',
                'address' => 'Cairo, Giza, Luxor, Aswan, Egypt',
                'address_ar' => 'القاهرة، الجيزة، الأقصر، أسوان، مصر',
                'city' => 'Cairo, Giza, Luxor, Aswan',
                'country' => 'Egypt',
                'cities_covered' => 'Cairo, Giza, Luxor, Aswan',
                'cities_covered_ar' => 'القاهرة، الجيزة، الأقصر، أسوان',
                'latitude' => null,
                'longitude' => null,
                'flexible_date' => 1,
                'day_nights' => '7 Days / 6 Nights',
                'person_capability' => 20,
                'price' => 300,
                'currency' => 'USD',
                'price_from' => 300,
                'price_to' => 450,
                'price_note' => 'Budget package: $300 – $450 per person. Standard package: $450 – $700 per person. Luxury package: $700 – $1,200+ per person. Prices vary depending on season, hotel level and availability.',
                'description' => 'Explore Egypt’s top highlights in one complete journey through history. Visit the Giza Pyramids and Sphinx, the Egyptian Museum and Old Cairo, Luxor Temples and Valley of the Kings, and enjoy a Nile experience in Aswan with an optional Hurghada beach extension.',
                'description_ar' => 'استكشف أبرز معالم مصر في رحلة كاملة عبر التاريخ. قم بزيارة أهرامات الجيزة وأبو الهول، والمتحف المصري والقاهرة القديمة، ومعابد الأقصر ووادي الملوك، واستمتع بتجربة نيلية في أسوان مع إمكانية إضافة امتداد شاطئي في الغردقة.',
                'destination_overview' => [
                    'departure_from' => 'Cairo Airport',
                    'arrival' => 'Cairo',
                    'transportation' => 'Domestic flights, airport transfers and guided tour transportation',
                    'accommodation' => '6 nights accommodation with breakfast',
                    'cities_covered' => 'Cairo, Giza, Luxor, Aswan',
                ],
                'departure_from_ar' => 'مطار القاهرة',
                'arrival_ar' => 'القاهرة',
                'transportation_ar' => 'رحلات داخلية، انتقالات المطار، ومواصلات للجولات السياحية',
                'accommodation_ar' => 'إقامة 6 ليالٍ مع الإفطار',
                'features' => [
                    ['icon' => 'fa-solid fa-landmark', 'feature' => 'Ancient history'],
                    ['icon' => 'fa-solid fa-palette', 'feature' => 'Culture'],
                    ['icon' => 'fa-solid fa-water', 'feature' => 'Nile experience'],
                    ['icon' => 'fa-solid fa-building-columns', 'feature' => 'Museums'],
                    ['icon' => 'fa-solid fa-mosque', 'feature' => 'Temples'],
                    ['icon' => 'fa-solid fa-map-location-dot', 'feature' => 'Guided tours'],
                ],
                'destination_features_ar' => [
                    ['icon' => 'fa-solid fa-landmark', 'feature' => 'تاريخ قديم'],
                    ['icon' => 'fa-solid fa-palette', 'feature' => 'ثقافة'],
                    ['icon' => 'fa-solid fa-water', 'feature' => 'تجربة نيلية'],
                    ['icon' => 'fa-solid fa-building-columns', 'feature' => 'متاحف'],
                    ['icon' => 'fa-solid fa-mosque', 'feature' => 'معابد'],
                    ['icon' => 'fa-solid fa-map-location-dot', 'feature' => 'جولات سياحية'],
                ],
                'highlights' => [
                    'Giza Pyramids and Sphinx',
                    'Egyptian Museum and Old Cairo',
                    'Luxor Temples and Valley of the Kings',
                    'Nile experience in Aswan',
                    'Optional Hurghada beach extension',
                ],
                'destination_highlights_ar' => [
                    'أهرامات الجيزة وأبو الهول',
                    'المتحف المصري والقاهرة القديمة',
                    'معابد الأقصر ووادي الملوك',
                    'تجربة نيلية في أسوان',
                    'امتداد شاطئي اختياري في الغردقة',
                ],
                'includes' => [
                    'Domestic flights',
                    'Hotels 4★ / upgrade available',
                    'Airport transfers',
                    'Guided tours',
                    'Nile experience in Aswan',
                ],
                'includes_ar' => [
                    'رحلات داخلية',
                    'فنادق 4 نجوم / إمكانية الترقية',
                    'انتقالات المطار',
                    'جولات سياحية بإرشاد محلي',
                    'تجربة نيلية في أسوان',
                ],
                'excludes' => [
                    'Visa',
                    'Entry tickets',
                    'Personal expenses',
                    'Optional Hurghada beach extension',
                    'Meals not mentioned',
                ],
                'excludes_ar' => [
                    'التأشيرة',
                    'تذاكر الدخول',
                    'المصاريف الشخصية',
                    'امتداد الغردقة الشاطئي الاختياري',
                    'الوجبات غير المذكورة',
                ],
                'itinerary_days' => [
                    ['day_number' => 'Day 1', 'title' => 'Arrival in Cairo', 'title_ar' => 'الوصول إلى القاهرة', 'description' => 'Airport transfer and hotel check-in.', 'description_ar' => 'الاستقبال من المطار وتسجيل الوصول إلى الفندق.'],
                    ['day_number' => 'Day 2', 'title' => 'Giza Pyramids & Sphinx', 'title_ar' => 'أهرامات الجيزة وأبو الهول', 'description' => 'Visit the pyramids, Sphinx and surrounding attractions.', 'description_ar' => 'زيارة الأهرامات وأبو الهول والمعالم المحيطة.'],
                    ['day_number' => 'Day 3', 'title' => 'Egyptian Museum & Old Cairo', 'title_ar' => 'المتحف المصري والقاهرة القديمة', 'description' => 'Discover priceless artifacts and historic landmarks.', 'description_ar' => 'اكتشاف القطع الأثرية والمعالم التاريخية.'],
                    ['day_number' => 'Day 4', 'title' => 'Travel to Luxor', 'title_ar' => 'السفر إلى الأقصر', 'description' => 'Visit Luxor temples and enjoy the city atmosphere.', 'description_ar' => 'زيارة معابد الأقصر والاستمتاع بأجواء المدينة.'],
                    ['day_number' => 'Day 5', 'title' => 'Valley of the Kings', 'title_ar' => 'وادي الملوك', 'description' => 'Explore ancient royal tombs and historical sites.', 'description_ar' => 'استكشاف المقابر الملكية القديمة والمواقع التاريخية.'],
                    ['day_number' => 'Day 6', 'title' => 'Nile Experience in Aswan', 'title_ar' => 'تجربة نيلية في أسوان', 'description' => 'Relax and enjoy the timeless beauty of the Nile.', 'description_ar' => 'الاسترخاء والاستمتاع بجمال النيل الخالد.'],
                    ['day_number' => 'Day 7', 'title' => 'Departure or Hurghada Extension', 'title_ar' => 'المغادرة أو امتداد الغردقة', 'description' => 'Transfer to airport or continue to optional Hurghada beach extension.', 'description_ar' => 'الانتقال إلى المطار أو متابعة الرحلة إلى امتداد شاطئي اختياري في الغردقة.'],
                ],
                'tour_start' => $baseDate->copy()->toDateTimeString(),
                'tour_end' => $baseDate->copy()->addDays(7)->toDateTimeString(),
            ],
            [
                'title' => 'Saudi Arabia Day Tours & Activities',
                'title_ar' => 'جولات وأنشطة يومية في السعودية',
                'tour_type' => 'Day Tours / Activities',
                'tour_type_ar' => 'جولات يومية / أنشطة',
                'package_label' => 'No Accommodation',
                'package_label_ar' => 'بدون إقامة',
                'address' => 'Riyadh, Saudi Arabia',
                'address_ar' => 'الرياض، المملكة العربية السعودية',
                'city' => 'Riyadh',
                'country' => 'Saudi Arabia',
                'cities_covered' => 'Riyadh',
                'cities_covered_ar' => 'الرياض',
                'latitude' => '24.7136',
                'longitude' => '46.6753',
                'flexible_date' => 1,
                'day_nights' => 'Day Tours',
                'person_capability' => 20,
                'price' => 30,
                'currency' => 'USD',
                'price_from' => 30,
                'price_to' => 120,
                'price_note' => 'Budget activities: $30 – $120 per person. Adventure and premium experiences: $120 – $300 per person. Prices vary depending on activity type, duration and availability.',
                'description' => 'Explore Saudi Arabia through flexible day tours and activities designed for travelers who want memorable experiences without accommodation. Choose from Edge of the World, Boulevard Riyadh City, Diriyah and Bujairi Terrace, or Riyadh Desert Safari.',
                'description_ar' => 'استكشف المملكة العربية السعودية من خلال جولات وأنشطة يومية مرنة مصممة للمسافرين الباحثين عن تجارب مميزة بدون إقامة. اختر بين حافة العالم، بوليفارد الرياض، الدرعية وبجيري تراس، أو سفاري صحراء الرياض.',
                'destination_overview' => [
                    'departure_from' => 'Riyadh',
                    'arrival' => 'Riyadh',
                    'transportation' => 'Comfortable transport with A/C available depending on selected activity',
                    'accommodation' => 'No accommodation included',
                    'cities_covered' => 'Riyadh',
                ],
                'departure_from_ar' => 'الرياض',
                'arrival_ar' => 'الرياض',
                'transportation_ar' => 'مواصلات مريحة ومكيفة حسب النشاط المختار',
                'accommodation_ar' => 'لا تشمل الإقامة',
                'features' => [
                    ['icon' => 'fa-solid fa-clock', 'feature' => 'Flexible schedules'],
                    ['icon' => 'fa-solid fa-user-group', 'feature' => 'Private and group options'],
                    ['icon' => 'fa-solid fa-car-side', 'feature' => 'Comfortable transport'],
                    ['icon' => 'fa-solid fa-user-tie', 'feature' => 'Expert local guides'],
                    ['icon' => 'fa-solid fa-tag', 'feature' => 'Best prices guaranteed'],
                ],
                'destination_features_ar' => [
                    ['icon' => 'fa-solid fa-clock', 'feature' => 'مواعيد مرنة'],
                    ['icon' => 'fa-solid fa-user-group', 'feature' => 'خيارات خاصة وجماعية'],
                    ['icon' => 'fa-solid fa-car-side', 'feature' => 'مواصلات مريحة'],
                    ['icon' => 'fa-solid fa-user-tie', 'feature' => 'مرشدون محليون خبراء'],
                    ['icon' => 'fa-solid fa-tag', 'feature' => 'أفضل الأسعار مضمونة'],
                ],
                'highlights' => [
                    'Flexible schedules',
                    'Private and group options',
                    'Comfortable transport',
                    'Expert local guides',
                    'Best prices guaranteed',
                ],
                'destination_highlights_ar' => [
                    'مواعيد مرنة',
                    'خيارات خاصة وجماعية',
                    'مواصلات مريحة',
                    'مرشدون محليون خبراء',
                    'أفضل الأسعار مضمونة',
                ],
                'includes' => [
                    'Local expert guides',
                    'Safe and comfortable transport',
                    'Flexible schedules',
                    'Private and group options',
                    'Booking support',
                ],
                'includes_ar' => [
                    'مرشدون محليون خبراء',
                    'مواصلات آمنة ومريحة',
                    'مواعيد مرنة',
                    'خيارات خاصة وجماعية',
                    'دعم الحجز',
                ],
                'excludes' => [
                    'Accommodation',
                    'Meals unless mentioned',
                    'Personal expenses',
                    'Optional paid activities',
                    'Entry tickets unless mentioned',
                ],
                'excludes_ar' => [
                    'الإقامة',
                    'الوجبات ما لم يتم ذكرها',
                    'المصاريف الشخصية',
                    'الأنشطة الاختيارية المدفوعة',
                    'تذاكر الدخول ما لم يتم ذكرها',
                ],
                'itinerary_days' => [
                    ['day_number' => 'Day 1', 'title' => 'Edge of the World Tour', 'title_ar' => 'جولة حافة العالم', 'description' => 'Desert adventure, hiking, photography and breathtaking panoramic views.', 'description_ar' => 'مغامرة صحراوية ومشي وتصوير وإطلالات بانورامية رائعة.'],
                    ['day_number' => 'Day 1', 'title' => 'Boulevard Riyadh City', 'title_ar' => 'بوليفارد الرياض', 'description' => 'Entertainment, restaurants, shows, rides and attractions.', 'description_ar' => 'ترفيه ومطاعم وعروض وألعاب ومعالم ممتعة.'],
                    ['day_number' => 'Day 1', 'title' => 'Diriyah & Bujairi Terrace', 'title_ar' => 'الدرعية وبجيري تراس', 'description' => 'Historic site, traditional Najdi architecture, luxury dining and cultural experience.', 'description_ar' => 'موقع تاريخي وعمارة نجدية تقليدية وتجربة طعام فاخرة وتجربة ثقافية.'],
                    ['day_number' => 'Day 1', 'title' => 'Desert Safari', 'title_ar' => 'سفاري الصحراء', 'description' => '4x4 dune bashing, optional camel ride, BBQ dinner and live entertainment.', 'description_ar' => 'قيادة على الكثبان الرملية بسيارات الدفع الرباعي وركوب جمال اختياري وعشاء باربكيو وعروض مباشرة.'],
                ],
                'tour_start' => $baseDate->copy()->toDateTimeString(),
                'tour_end' => $baseDate->copy()->addDay()->toDateTimeString(),
                'image' => $image,
            ],
            [
                'title' => 'Saudi Arabia Premium Experiences',
                'title_ar' => 'تجارب السعودية المميزة',
                'tour_type' => 'Premium Experiences / Adventure',
                'tour_type_ar' => 'تجارب مميزة / مغامرة',
                'package_label' => 'No Accommodation',
                'package_label_ar' => 'بدون إقامة',
                'address' => 'AlUla & Red Sea, Saudi Arabia',
                'address_ar' => 'العلا والبحر الأحمر، المملكة العربية السعودية',
                'city' => 'AlUla, Red Sea',
                'country' => 'Saudi Arabia',
                'cities_covered' => 'AlUla, Red Sea',
                'cities_covered_ar' => 'العلا، البحر الأحمر',
                'latitude' => null,
                'longitude' => null,
                'flexible_date' => 1,
                'day_nights' => 'Premium Experiences',
                'person_capability' => 20,
                'price' => 150,
                'currency' => 'USD',
                'price_from' => 150,
                'price_to' => 300,
                'price_note' => 'AlUla day tour: $150 – $300 per person. Red Sea water sports: $50 – $150 per person. Prices vary depending on selected experience, season and availability.',
                'description' => 'Enjoy Saudi Arabia’s premium experiences through exclusive adventures and unforgettable memories. Discover the ancient wonders of AlUla, visit Hegra, Elephant Rock and AlUla Old Town, or enjoy water sports in the Red Sea with snorkeling, diving, jet ski, surfing and boat trips.',
                'description_ar' => 'استمتع بتجارب السعودية المميزة من خلال مغامرات حصرية وذكريات لا تُنسى. اكتشف عجائب العلا القديمة مثل الحجر وصخرة الفيل والبلدة القديمة، أو استمتع بالرياضات المائية في البحر الأحمر مثل السنوركلينج والغوص والجيت سكي وركوب الأمواج ورحلات القوارب.',
                'destination_overview' => [
                    'departure_from' => 'AlUla or Red Sea area',
                    'arrival' => 'AlUla / Red Sea',
                    'transportation' => 'Local transfers depending on selected experience',
                    'accommodation' => 'No accommodation included',
                    'cities_covered' => 'AlUla, Red Sea',
                ],
                'departure_from_ar' => 'العلا أو منطقة البحر الأحمر',
                'arrival_ar' => 'العلا / البحر الأحمر',
                'transportation_ar' => 'انتقالات محلية حسب التجربة المختارة',
                'accommodation_ar' => 'لا تشمل الإقامة',
                'features' => [
                    ['icon' => 'fa-solid fa-user-tie', 'feature' => 'Professional local guide'],
                    ['icon' => 'fa-solid fa-shield-halved', 'feature' => 'Safe and secure'],
                    ['icon' => 'fa-solid fa-user-group', 'feature' => 'Private and group options'],
                    ['icon' => 'fa-solid fa-clock', 'feature' => 'Flexible schedules'],
                    ['icon' => 'fa-solid fa-star', 'feature' => 'Top quality experiences'],
                ],
                'destination_features_ar' => [
                    ['icon' => 'fa-solid fa-user-tie', 'feature' => 'مرشد محلي محترف'],
                    ['icon' => 'fa-solid fa-shield-halved', 'feature' => 'آمن وموثوق'],
                    ['icon' => 'fa-solid fa-user-group', 'feature' => 'خيارات خاصة وجماعية'],
                    ['icon' => 'fa-solid fa-clock', 'feature' => 'مواعيد مرنة'],
                    ['icon' => 'fa-solid fa-star', 'feature' => 'تجارب عالية الجودة'],
                ],
                'highlights' => [
                    'Expert local guides',
                    'Safe and secure',
                    'Private and group options',
                    'Flexible schedules',
                    'Top quality experiences',
                ],
                'destination_highlights_ar' => [
                    'مرشدون محليون خبراء',
                    'آمن وموثوق',
                    'خيارات خاصة وجماعية',
                    'مواعيد مرنة',
                    'تجارب عالية الجودة',
                ],
                'includes' => [
                    'Professional local guide',
                    'Selected experience support',
                    'Safety gear where required',
                    'Private and group options',
                    'Flexible schedules',
                    'Booking support',
                ],
                'includes_ar' => [
                    'مرشد محلي محترف',
                    'دعم التجربة المختارة',
                    'معدات السلامة عند الحاجة',
                    'خيارات خاصة وجماعية',
                    'مواعيد مرنة',
                    'دعم الحجز',
                ],
                'excludes' => [
                    'Accommodation',
                    'Meals unless mentioned',
                    'Personal expenses',
                    'Optional activities',
                    'Transportation unless included in selected option',
                ],
                'excludes_ar' => [
                    'الإقامة',
                    'الوجبات ما لم يتم ذكرها',
                    'المصاريف الشخصية',
                    'الأنشطة الاختيارية',
                    'المواصلات ما لم تكن ضمن الخيار المختار',
                ],
                'itinerary_days' => [
                    ['day_number' => 'Experience 1', 'title' => 'AlUla Day Tour', 'title_ar' => 'جولة يومية في العلا', 'description' => 'Visit Hegra UNESCO World Heritage Site, Elephant Rock, desert canyons and AlUla Old Town with a professional local guide.', 'description_ar' => 'زيارة الحجر المدرج ضمن قائمة اليونسكو وصخرة الفيل والأودية الصحراوية والبلدة القديمة في العلا مع مرشد محلي محترف.'],
                    ['day_number' => 'Experience 2', 'title' => 'Water Sports in the Red Sea', 'title_ar' => 'الرياضات المائية في البحر الأحمر', 'description' => 'Enjoy jet ski, surfing, paddle boarding, snorkeling, diving, boat trips and island hopping with safety support.', 'description_ar' => 'الاستمتاع بالجيت سكي وركوب الأمواج والتجديف والسنوركلينج والغوص ورحلات القوارب والتنقل بين الجزر مع دعم السلامة.'],
                ],
                'tour_start' => $baseDate->copy()->toDateTimeString(),
                'tour_end' => $baseDate->copy()->addDay()->toDateTimeString(),
                'image' => $image,
            ],
            [
                'title' => 'Vietnam 8 Days 7 Nights Travel Package',
                'title_ar' => 'باقة فيتنام 8 أيام / 7 ليالي',
                'tour_type' => 'International Travel Package',
                'tour_type_ar' => 'باقة سفر دولية',
                'package_label' => '8 Days / 7 Nights',
                'package_label_ar' => '8 أيام / 7 ليالي',
                'address' => 'Vietnam',
                'address_ar' => 'فيتنام',
                'city' => 'Hanoi, Ha Long Bay, Da Nang, Hoi An',
                'country' => 'Vietnam',
                'cities_covered' => 'Hanoi, Ha Long Bay, Da Nang, Hoi An',
                'cities_covered_ar' => 'هانوي، خليج ها لونغ، دا نانغ، هوي آن',
                'latitude' => null,
                'longitude' => null,
                'day_nights' => '8 Days / 7 Nights',
                'person_capability' => 20,
                'price' => 750,
                'currency' => 'USD',
                'price_from' => 750,
                'price_to' => 1200,
                'price_note' => 'Estimated price per person. Final price may vary by season, hotel availability, flight timing, and private tour options.',
                'description' => 'Discover Vietnam in an 8-day journey covering Hanoi, Ha Long Bay, Da Nang, and Hoi An. This package combines city culture, natural beauty, a Ha Long Bay cruise, the famous Golden Bridge at Ba Na Hills, and the magical lantern streets of Hoi An.',
                'description_ar' => 'اكتشف فيتنام في رحلة مميزة لمدة 8 أيام تشمل هانوي، خليج ها لونغ، دا نانغ، وهوي آن. تجمع هذه الباقة بين الثقافة، والطبيعة، ورحلة بحرية في خليج ها لونغ، وزيارة الجسر الذهبي في با نا هيلز، وأجواء شوارع الفوانيس الساحرة في هوي آن.',
                'destination_overview' => [
                    'departure_from' => 'Airport / Client location',
                    'arrival' => 'Hanoi',
                    'transportation' => 'Private transfers, domestic flights, cruise transfer, and local transportation during tours.',
                    'accommodation' => '4-star hotels or similar with breakfast, plus 1-night cruise accommodation in Ha Long Bay.',
                    'cities_covered' => 'Hanoi, Ha Long Bay, Da Nang, Hoi An',
                ],
                'departure_from_ar' => 'المطار / موقع العميل',
                'arrival_ar' => 'هانوي',
                'transportation_ar' => 'انتقالات خاصة، رحلات داخلية، انتقالات الكروز، ومواصلات محلية أثناء الجولات.',
                'accommodation_level' => '4-star hotels or similar',
                'accommodation_ar' => 'فنادق 4 نجوم أو ما يعادلها مع الإفطار، بالإضافة إلى إقامة ليلة واحدة على الكروز في خليج ها لونغ.',
                'highlights' => [
                    'Hanoi city tour',
                    'Ha Long Bay overnight cruise',
                    'Kayaking and cave visit',
                    'Ba Na Hills and Golden Bridge',
                    'Hoi An ancient town walking tour',
                    'Lantern streets experience',
                ],
                'destination_highlights_ar' => [
                    'جولة في مدينة هانوي',
                    'رحلة بحرية ومبيت في خليج ها لونغ',
                    'كاياك وزيارة الكهوف',
                    'با نا هيلز والجسر الذهبي',
                    'جولة مشي في مدينة هوي آن القديمة',
                    'تجربة شوارع الفوانيس',
                ],
                'features' => $this->featureRows([
                    ['fa-solid fa-city', 'City tour', 'جولة في المدينة'],
                    ['fa-solid fa-ship', 'Overnight cruise', 'رحلة بحرية ومبيت'],
                    ['fa-solid fa-water', 'Kayaking', 'التجديف بالكاياك'],
                    ['fa-solid fa-mountain-sun', 'Golden Bridge', 'الجسر الذهبي'],
                    ['fa-solid fa-umbrella-beach', 'Hoi An lanterns', 'فوانيس هوي آن'],
                    ['fa-solid fa-hotel', '4-star stays', 'إقامة 4 نجوم'],
                ]),
                'destination_features_ar' => $this->destinationFeatureRows([
                    ['fa-solid fa-city', 'جولة في المدينة'],
                    ['fa-solid fa-ship', 'رحلة بحرية ومبيت'],
                    ['fa-solid fa-water', 'التجديف بالكاياك'],
                    ['fa-solid fa-mountain-sun', 'الجسر الذهبي'],
                    ['fa-solid fa-umbrella-beach', 'فوانيس هوي آن'],
                    ['fa-solid fa-hotel', 'إقامة 4 نجوم'],
                ]),
                'includes' => [
                    'Accommodation with breakfast',
                    '1-night cruise in Ha Long Bay',
                    'Domestic flights',
                    'All transfers',
                    'English-speaking guide',
                    'Entrance fees and tours',
                ],
                'includes_ar' => [
                    'الإقامة مع الإفطار',
                    'ليلة واحدة على كروز في خليج ها لونغ',
                    'الطيران الداخلي',
                    'جميع الانتقالات',
                    'مرشد سياحي باللغة الإنجليزية',
                    'رسوم الدخول والجولات السياحية',
                ],
                'excludes' => [
                    'International flights',
                    'Visa',
                    'Personal expenses',
                ],
                'excludes_ar' => [
                    'الطيران الدولي',
                    'التأشيرة',
                    'المصروفات الشخصية',
                ],
                'itinerary_days' => [
                    [
                        'day_number' => 'Day 1',
                        'title' => 'Arrival in Hanoi',
                        'title_ar' => 'الوصول إلى هانوي',
                        'description' => 'Meet and assist at the airport, transfer to the hotel, and enjoy free time to relax or explore nearby areas.',
                        'description_ar' => 'الاستقبال والمساعدة في المطار، ثم الانتقال إلى الفندق والاستمتاع بوقت حر للراحة أو استكشاف المناطق القريبة.',
                    ],
                    [
                        'day_number' => 'Day 2',
                        'title' => 'Hanoi City Tour',
                        'title_ar' => 'جولة في مدينة هانوي',
                        'description' => 'Visit Ho Chi Minh Complex, Temple of Literature, Old Quarter, and enjoy a traditional Cyclo ride.',
                        'description_ar' => 'زيارة مجمع هو تشي منه، ومعبد الأدب، والحي القديم، مع تجربة ركوب السيكلو التقليدية.',
                    ],
                    [
                        'day_number' => 'Day 3',
                        'title' => 'Ha Long Bay Cruise',
                        'title_ar' => 'رحلة كروز في خليج ها لونغ',
                        'description' => 'Transfer to Ha Long Bay, board the cruise, enjoy lunch, kayaking, cave visits, and overnight on the cruise.',
                        'description_ar' => 'الانتقال إلى خليج ها لونغ، والصعود إلى الكروز، والاستمتاع بالغداء، والكاياك، وزيارة الكهوف، والمبيت على الكروز.',
                    ],
                    [
                        'day_number' => 'Day 4',
                        'title' => 'Ha Long Bay to Hanoi',
                        'title_ar' => 'من خليج ها لونغ إلى هانوي',
                        'description' => 'Enjoy morning cruise activities, breakfast on board, then return to Hanoi.',
                        'description_ar' => 'الاستمتاع بأنشطة صباحية على الكروز، وتناول الإفطار على متن القارب، ثم العودة إلى هانوي.',
                    ],
                    [
                        'day_number' => 'Day 5',
                        'title' => 'Flight to Da Nang',
                        'title_ar' => 'الطيران إلى دا نانغ',
                        'description' => 'Transfer to the airport for the domestic flight to Da Nang, then hotel check-in and free time.',
                        'description_ar' => 'الانتقال إلى المطار للسفر الداخلي إلى دا نانغ، ثم تسجيل الوصول إلى الفندق والاستمتاع بوقت حر.',
                    ],
                    [
                        'day_number' => 'Day 6',
                        'title' => 'Ba Na Hills Tour',
                        'title_ar' => 'جولة با نا هيلز',
                        'description' => 'Visit Ba Na Hills, enjoy the cable car, Golden Bridge, French Village, and mountain views.',
                        'description_ar' => 'زيارة با نا هيلز، والاستمتاع بالتلفريك، والجسر الذهبي، والقرية الفرنسية، والإطلالات الجبلية.',
                    ],
                    [
                        'day_number' => 'Day 7',
                        'title' => 'Hoi An Ancient Town Tour',
                        'title_ar' => 'جولة مدينة هوي آن القديمة',
                        'description' => 'Explore Hoi An ancient town, Japanese Bridge, local streets, and the famous lantern atmosphere.',
                        'description_ar' => 'استكشاف مدينة هوي آن القديمة، والجسر الياباني، والشوارع المحلية، وأجواء الفوانيس الشهيرة.',
                    ],
                    [
                        'day_number' => 'Day 8',
                        'title' => 'Departure',
                        'title_ar' => 'المغادرة',
                        'description' => 'Transfer to the airport for final departure.',
                        'description_ar' => 'الانتقال إلى المطار للمغادرة النهائية.',
                    ],
                ],
                'duration_days' => 8,
            ],
            [
                'title' => 'Bosnia and Herzegovina 8 Days 7 Nights Travel Package',
                'title_ar' => 'باقة البوسنة والهرسك 8 أيام / 7 ليالي',
                'tour_type' => 'International Travel Package',
                'tour_type_ar' => 'باقة سفر دولية',
                'package_label' => '8 Days / 7 Nights',
                'package_label_ar' => '8 أيام / 7 ليالي',
                'address' => 'Bosnia and Herzegovina',
                'address_ar' => 'البوسنة والهرسك',
                'city' => 'Sarajevo, Mostar, Jajce, Travnik',
                'country' => 'Bosnia and Herzegovina',
                'cities_covered' => 'Sarajevo, Mostar, Jajce, Travnik',
                'cities_covered_ar' => 'سراييفو، موستار، يايتسه، ترافنيك',
                'latitude' => null,
                'longitude' => null,
                'day_nights' => '8 Days / 7 Nights',
                'person_capability' => 20,
                'price' => 700,
                'currency' => 'EUR',
                'price_from' => 700,
                'price_to' => 1200,
                'price_note' => 'Estimated price per person for 4-star accommodation. Final price may change depending on season, hotel availability, and private tour arrangements.',
                'description' => 'Experience Bosnia and Herzegovina in an 8-day journey through Sarajevo, Mostar, Jajce, and Travnik. This package combines Ottoman heritage, old towns, bridges, waterfalls, mountain nature, and cultural landmarks in one memorable trip.',
                'description_ar' => 'استمتع برحلة مميزة في البوسنة والهرسك لمدة 8 أيام تشمل سراييفو، موستار، يايتسه، وترافنيك. تجمع هذه الباقة بين التراث العثماني، والمدن القديمة، والجسور التاريخية، والشلالات، والطبيعة الجبلية، والمعالم الثقافية.',
                'destination_overview' => [
                    'departure_from' => 'Airport / Client location',
                    'arrival' => 'Sarajevo',
                    'transportation' => 'Private transfers and local transportation between Sarajevo, Mostar, Jajce, and Travnik.',
                    'accommodation' => '4-star hotels or similar with daily breakfast.',
                    'cities_covered' => 'Sarajevo, Mostar, Jajce, Travnik',
                ],
                'departure_from_ar' => 'المطار / موقع العميل',
                'arrival_ar' => 'سراييفو',
                'transportation_ar' => 'انتقالات خاصة ومواصلات محلية بين سراييفو وموستار ويايتسه وترافنيك.',
                'accommodation_level' => '4-star hotels or similar',
                'accommodation_ar' => 'فنادق 4 نجوم أو ما يعادلها مع إفطار يومي.',
                'highlights' => [
                    'Sarajevo old town tour',
                    'Latin Bridge and Tunnel Museum',
                    'Mostar Old Bridge',
                    'Kravice Waterfalls',
                    'Blagaj Tekke and Pocitelj village',
                    'Jajce waterfalls and lakes',
                    'Travnik fortress',
                    'Nature tour to Bijambare caves or mountains',
                ],
                'destination_highlights_ar' => [
                    'جولة في مدينة سراييفو القديمة',
                    'الجسر اللاتيني ومتحف النفق',
                    'جسر موستار القديم',
                    'شلالات كرافيتسه',
                    'تكية بلاجاي وقرية بوتشيتلي',
                    'شلالات وبحيرات يايتسه',
                    'قلعة ترافنيك',
                    'جولة طبيعية إلى كهوف بيامباري أو الجبال',
                ],
                'features' => $this->featureRows([
                    ['fa-solid fa-mosque', 'Ottoman heritage', 'التراث العثماني'],
                    ['fa-solid fa-bridge', 'Historic bridges', 'الجسور التاريخية'],
                    ['fa-solid fa-waterfall', 'Waterfalls', 'الشلالات'],
                    ['fa-solid fa-mountain-sun', 'Mountain nature', 'الطبيعة الجبلية'],
                    ['fa-solid fa-landmark', 'Old towns', 'المدن القديمة'],
                    ['fa-solid fa-compass', 'Cultural landmarks', 'معالم ثقافية'],
                ]),
                'destination_features_ar' => $this->destinationFeatureRows([
                    ['fa-solid fa-mosque', 'التراث العثماني'],
                    ['fa-solid fa-bridge', 'الجسور التاريخية'],
                    ['fa-solid fa-waterfall', 'الشلالات'],
                    ['fa-solid fa-mountain-sun', 'الطبيعة الجبلية'],
                    ['fa-solid fa-landmark', 'المدن القديمة'],
                    ['fa-solid fa-compass', 'معالم ثقافية'],
                ]),
                'includes' => [
                    'Hotel accommodation with breakfast',
                    'Transfers',
                    'Guided tours',
                    'Entrance tickets',
                ],
                'includes_ar' => [
                    'الإقامة الفندقية مع الإفطار',
                    'الانتقالات',
                    'الجولات السياحية مع مرشد',
                    'تذاكر الدخول',
                ],
                'excludes' => [
                    'Flights',
                    'Lunch and dinner',
                    'Personal expenses',
                ],
                'excludes_ar' => [
                    'الطيران',
                    'الغداء والعشاء',
                    'المصروفات الشخصية',
                ],
                'itinerary_days' => [
                    [
                        'day_number' => 'Day 1',
                        'title' => 'Arrival in Sarajevo',
                        'title_ar' => 'الوصول إلى سراييفو',
                        'description' => 'Meet and transfer to the hotel, then enjoy free time to relax or explore the city.',
                        'description_ar' => 'الاستقبال والانتقال إلى الفندق، ثم الاستمتاع بوقت حر للراحة أو استكشاف المدينة.',
                    ],
                    [
                        'day_number' => 'Day 2',
                        'title' => 'Sarajevo City Tour',
                        'title_ar' => 'جولة في مدينة سراييفو',
                        'description' => 'Visit the Old Town Bascarsija, Latin Bridge, Tunnel Museum, and key cultural landmarks.',
                        'description_ar' => 'زيارة المدينة القديمة باشارشيا، والجسر اللاتيني، ومتحف النفق، وأهم المعالم الثقافية.',
                    ],
                    [
                        'day_number' => 'Day 3',
                        'title' => 'Sarajevo to Mostar',
                        'title_ar' => 'من سراييفو إلى موستار',
                        'description' => 'Travel from Sarajevo to Mostar with a stop at Konjic, visit the Old Bridge, and overnight in Mostar.',
                        'description_ar' => 'الانتقال من سراييفو إلى موستار مع التوقف في كونيتس، وزيارة الجسر القديم، والمبيت في موستار.',
                    ],
                    [
                        'day_number' => 'Day 4',
                        'title' => 'Herzegovina Tour',
                        'title_ar' => 'جولة الهرسك',
                        'description' => 'Visit Kravice Waterfalls, Blagaj Tekke, and Pocitelj village in a full-day cultural and nature tour.',
                        'description_ar' => 'زيارة شلالات كرافيتسه، وتكية بلاجاي، وقرية بوتشيتلي في جولة تجمع بين الطبيعة والثقافة.',
                    ],
                    [
                        'day_number' => 'Day 5',
                        'title' => 'Mostar to Jajce',
                        'title_ar' => 'من موستار إلى يايتسه',
                        'description' => 'Travel to Jajce, visit waterfalls, lakes, and traditional mills.',
                        'description_ar' => 'الانتقال إلى يايتسه، وزيارة الشلالات، والبحيرات، والطواحين التقليدية.',
                    ],
                    [
                        'day_number' => 'Day 6',
                        'title' => 'Jajce to Travnik to Sarajevo',
                        'title_ar' => 'من يايتسه إلى ترافنيك ثم سراييفو',
                        'description' => 'Visit Travnik Fortress, enjoy the old town atmosphere, then return to Sarajevo.',
                        'description_ar' => 'زيارة قلعة ترافنيك، والاستمتاع بأجواء المدينة القديمة، ثم العودة إلى سراييفو.',
                    ],
                    [
                        'day_number' => 'Day 7',
                        'title' => 'Nature Tour',
                        'title_ar' => 'جولة طبيعية',
                        'description' => 'Enjoy a nature tour to Bijambare caves or nearby mountain areas.',
                        'description_ar' => 'الاستمتاع بجولة طبيعية إلى كهوف بيامباري أو المناطق الجبلية القريبة.',
                    ],
                    [
                        'day_number' => 'Day 8',
                        'title' => 'Departure',
                        'title_ar' => 'المغادرة',
                        'description' => 'Transfer to the airport for final departure.',
                        'description_ar' => 'الانتقال إلى المطار للمغادرة النهائية.',
                    ],
                ],
                'duration_days' => 8,
            ],
        ];
    }

    private function featureRows(array $rows): array
    {
        return array_map(static function (array $row): array {
            return [
                'icon' => $row[0],
                'feature' => $row[1],
                'feature_ar' => $row[2],
            ];
        }, $rows);
    }

    private function destinationFeatureRows(array $rows): array
    {
        return array_map(static function (array $row): array {
            return [
                'icon' => $row[0],
                'feature_ar' => $row[1],
            ];
        }, $rows);
    }
}
